version: '3'
services:
  db:
    image: mdillon/postgis:11-alpine
  
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      PGDATABASE: mesolex
      PGUSER: postgres
      PGHOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
      - search
    volumes:
      - .:/code

volumes:
  pgdata: