---
env_name: dev
repo_branch: develop
domain: dev.mesolex.org

certbot_create_if_missing: true
certbot_certs:
  - email: "{{ admin_email }}"
    domains:
      - dev.mesolex.org

cert_source: letsencrypt
force_ssl: true

requirements_file: "{{ source_dir }}/requirements/base.txt"

source_is_local: false
gunicorn_num_workers: 1

ansible_python_interpreter: "/usr/bin/python3"