---
- hosts: db
  become: yes
  roles:
    - tequila-postgresql
  post_tasks:
    - name: enable fuzzystrmatch
      become_user: postgres
      become: yes
      postgresql_ext:
        name: fuzzystrmatch
        db: "{{ db_name }}"
    - name: enable unaccent
      become_user: postgres
      become: yes
      postgresql_ext:
        name: unaccent
        db: "{{ db_name }}"
