---
- name: Localization
  hosts: web
  become: yes
  tasks:
    - name: install app packages
      apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - gettext
        - libgettextpo-dev
    - name: Compile messages
      django_manage:
        command: compilemessages
        app_path: "{{ source_dir }}"
        virtualenv: "{{ venv_dir }}"
      become_user: "{{ project_user }}"
