---
- src: https://github.com/caktus/tequila-common
  version: v0.9.2
  name: tequila-common

- src: https://github.com/nmashton/tequila-postgresql
  version: ansible-3-updates
  name: tequila-postgresql

- src: https://github.com/caktus/tequila-nginx
  version: v0.8.12
  name: tequila-nginx

- src: https://github.com/caktus/tequila-django
  version: v0.9.28
  name: tequila-django

- src: geerlingguy.nodejs
  version: 4.2.2
  name: nodejs

- src: https://github.com/caktus/tequila-nodejs
  version: v0.8.2
  name: tequila-nodejs

- src: elastic.elasticsearch
  version: v7.11.1
