---
- src: https://github.com/caktus/tequila-common
  version: v0.8.4
  name: tequila-common

- src: https://github.com/caktus/tequila-postgresql
  version: v0.8.0
  name: tequila-postgresql

- src: https://github.com/caktus/tequila-nginx
  version: v0.8.0
  name: tequila-nginx

- src: https://github.com/caktus/tequila-django
  version: v0.9.13
  name: tequila-django

- src: https://github.com/caktus/tequila-nodejs
  version: v0.8.0
  name: tequila-nodejs

- src: geerlingguy.java
  version: 1.8.1
  name: java

- src: geerlingguy.solr
  version: 4.1.0
  name: solr

- src: geerlingguy.nodejs
  version: 4.2.0
  name: nodejs
