# Configuration for the languages supported by Mesolex.
# Used to set up Django forms and front-end components.
---
# Mayan languages :: maya1287
chol1282:
    label: Chol
    code: chol1282
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []
chuj1250:
    label: Chuj
    code: chuj1250
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []

# Amuzgo-Mixtecan languages :: amuz1253
## Mixtec
yolo1241:
    label: Mixteco de Yoloxóchitl
    code: yolo1241
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []
juxt1241:
    label: Mixteco de San Martín Duraznos
    code: juxt1241
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []
magd1235:
    label: Mixteco de Magdalena Peñascos
    code: magd1235
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []
mixt1247:
    label: La reconstrucción del mixteco
    code: mixt1247
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []
xoch1238:
    label: Mixteco de Xochapan
    code: xoch1238
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []

## Triqui
trq:
    label: Triqui de San Martín Itunyoso
    code: sanm1298
    filterable_fields:
        - field: lemma
          label: Entrada
          terms:
            - lemma
    global_filters: []
    elasticsearch_fields:
        - field: precise_meaning
          label: Significado preciso
          terms:
            - definitions_es
        - field: illustrative_phrases
          label: Frase ilustrativas
          terms:
            - quotations_trq
            - quotations_es
    controlled_vocab_fields: []
chic1273:
    label: Triqui de Chicahuaxtla
    code: chic1273
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []

# Uto-Aztecan :: utoa1244
## Nahuatl
azz:
    label: Náhuat de la Sierra Nororiental de Puebla
    code: azz
    extra_fields:
      - field: vln
        label: Neutralizar cantidad vocálica
        constraints:
          - no_regex
      - field: nahuat_orthography
        label: Activar flexibilidad ortográfica
        constraints:
          - no_regex
    global_filters:
      - field: only_with_sound
        label: Sólo mostrar entradas con sonidos
    filterable_fields:
        - field: lemma
          label: Entrada
          terms:
            - lemma
            - variant__value
        - field: gloss
          label: Glosa
          terms:
            - gloss__value
        - field: root
          label: Raiz
          terms:
            - root__value
        - field: category
          label: Campo semántico
          terms:
            - category__value
        - field: part_of_speech
          label: Categoría gramatical
          terms:
            - grammargroup__part_of_speech
        - field: inflectional_type
          label: Inflexión
          terms:
            - grammargroup__inflectional_type
    elasticsearch_fields:
        - field: precise_meaning
          label: Significado preciso
          terms:
            - definitions_es
        - field: extended_meaning
          label: Significado extendido
          terms:
            - definitions_es
            - ostentives_es
        - field: illustrative_phrases
          label: Frase ilustrativas
          terms:
            - quotations_azz
            - quotations_es
        - field: complete_search
          label: Búsqueda exhaustiva
          terms:
            - definitions_es
            - quotations_es
            - ostentives_es
    controlled_vocab_fields:
        - field: part_of_speech
          items:
            - value: Adj
              label: Adjetivo
            - value: Adv
              label: Adverbio
            - value: Aux
              label: Auxiliar
            - value: Bebe
              label: Habla-de-niños
            - value: Clítico
              label: Clítico
            - value: Conjunc
              label: Conjunción
            - value: Copula
              label: Cópula
            - value: Demostrativo
              label: Demostrativo
            - value: Direccional
              label: Direccional
            - value: Estativo
              label: Estativo
            - value: Interj
              label: Interjección
            - value: Interrogativo
              label: Interrogativo
            - value: Locativo
              label: Locativo
            - value: Modal
              label: Modal
            - value: Muletilla
              label: Muletilla
            - value: Neg
              label: Negación
            - value: Prefijo
              label: Prefijo
            - value: Preposición
              label: Preposición
            - value: Pronombre
              label: Pronombre
            - value: Saludo
              label: Saludo
            - value: Subord
              label: Subordinador
            - value: Sufijo
              label: Sufijo
            - value: Sust
              label: Sustantivo
            - value: Terminación aspectual
              label: Terminación-aspectual
            - value: Topónimo
              label: Topónimo
            - value: V0
              label: Verbo-impersonal
            - value: V1
              label: Verbo-intransitivo
            - value: V2
              label: Verbo-transitivo
            - value: V3
              label: Verbo-bitransitivo
            - value: V4
              label: Verbo-tritransitivo
            - value: Vocativo
              label: Vocativo
        - field: inflectional_type
          items:
            - value: Clase 1
              label: Verbo clase 1 (kwa)
            - value: Clase 2a
              label: Verbo clase 2a (pale:wia)
            - value: Clase 2b
              label: Verbo clase 2b (polowa)
            - value: Clase 3
              label: Verbo clase 3 (kalaki)
            - value: Clase 4
              label: Verbo clase 4 (cho:ka)
            - value: Clase 4-3
              label: Verbo clase 4-3 (ki:sa)
            - value: Clase 4-3/3
              label: Verbo clase 4-3/3 (pata:ni)
            - value: N1
              label: Solamente no posesionado
            - value: N1, N2
              label: Posesión enajenable y no enajenable
            - value: N1=N2
              label: Posesión enajenable y no enajenable (no cambio de raíz)
            - value: Oblig        
              label: Obligatoriamente posesionado
isth1242:
    label: Náhuatl de Mecayapan
    code: isth1242
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []
pipi1250:
    label: Pipil (Nawat)
    code: pipi1250
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []

# Totonacan
high1243:
    label: Totonaco de Zongozotla
    code: high1243
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []
ozln:
    label: Totonaco de Ozelonacaxtla
    code: ozln
    filterable_fields: []
    global_filters: []
    elasticsearch_fields: []
    controlled_vocab_fields: []