---
project_name: mesolex
python_version: 3.7
pg_version: 11

es_version: 7.8.0
es_use_repository: false
es_custom_package_url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.8.0-amd64.deb"
es_instance_name: mesolex
es_enable_xpack: false
es_config:
  network.host: 0.0.0.0
  discovery.type: "single-node"
es_heap_size: 256m

secret_key: "{{ SECRET_KEY }}"

root_dir: "/var/www/{{ project_name }}"
source_dir: "{{ root_dir }}/src"
venv_dir: "{{ root_dir }}/env"
project_user: "{{ project_name }}"
client_max_body_size: "50M"

db_password: "{{ SECRET_DB_PASSWORD }}"
app_minions: "{{ groups['web'] | union(groups['worker']) }}"

repo:
  url: "{{ repo_url|default('git@github.com:nmashton/mesolex.git') }}"
  branch: "{{ repo_branch|default('master') }}"

github_deploy_key: "{{ SECRET_GITHUB_DEPLOY_KEY|default('') }}"

nodejs_version: "12.x"
nodejs_install_npm_user: "{{ project_name }}"
nodejs_package_json_path: "{{ source_dir }}"
nodejs_config_unsafe_perm: true
ignore_devdependencies: true